### PR TITLE
Embed a notebook in a React app

### PR DESCRIPTION
**Pull request by eagereyes**
Migrates [Embed a notebook in a React app](https://observablehq.com/@observablehq/how-to-embed-a-notebook-in-a-react-app)

### CODE REVIEW

**Comment by mootari** [comment]
Are we planning to convert QuickTime videos to a more commonly support format like MPEG-4?

**Comment by eagereyes** [comment]
Is there a browser or platform that doesn't support them at this point?

**Review by jpe442 — APPROVED** [review]
LGTM! 🚢

**Comment by mootari** [comment]
> Is there a browser or platform that doesn't support them at this point?

I wasn't able to find a list of the current browser support, but based on my own tests it's a lot better than I expected:
- Tested on Windows 11 and Windows 10 in Firefox 116 (via SauceLabs)
- Tested on Android 10 (device) and 11 (via emulator)

**Pull request merged**
