### PR TITLE
Remove Microsoft Teams docs

### PR DESCRIPTION
**Pull request by annie**
We are pruning our Microsoft Teams integration ✂️ 

Part of https://github.com/observablehq/observablehq/issues/14948

### CODE REVIEW

**Comment by eagereyes** [comment]
We also need to remove the redirect from `/@observablehq/ms-teams-integration` to `/documentation/accounts-workspaces/microsoft-teams-integration` before we deploy this (and edit that notebook once we can get to it again)

**Comment by eagereyes** [comment]
The redirect from the old notebook is gone, so we can merge this as soon as it's ready :)

**Comment by annie** [comment]
good catch @eagereyes! i just went through and removed the images.

**Review by eagereyes — APPROVED** [review]
Great, thanks for deleting the images! LGTM!

**Pull request merged**
