### PR TITLE
Fix Google Analytics code

### PR DESCRIPTION
**Pull request by eagereyes**
I also ran prettier, which reformatted the entire file, the only actual changes are in the head part to break the code up into multiple lines since `\n` doesn't seem to work.

### CODE REVIEW

**Review by mbostock — CHANGES_REQUESTED** [review]
Can you revert the Prettier changes please so that it’s easier to see what you’ve changed? If you want to adopt Prettier, that should be done as a separate PR apart from functional changes.

**Comment by eagereyes** [comment]
Okay, done! It's just to turn the GA code into separate lines instead of using `\n`, which just seems to get removed rather than rendered as newlines. The result is that the GA code doesn't seem to work (same for Plot btw, we're not getting GA events).

**Comment by mbostock** [comment]
I don’t see that the newlines are required. Looking at the source of the current site, this

```js
window.dataLayer=window.dataLayer||[];function gtag(){dataLayer.push(arguments)}gtag("js",new Date),gtag("config","G-9B88TP6PKQ");
```

is equivalent to this via Prettier

```js
window.dataLayer = window.dataLayer || [];
function gtag() {
  dataLayer.push(arguments);
}
gtag("js", new Date()), gtag("config", "G-9B88TP6PKQ");
```

and so changing the newlines shouldn’t have any effect. Can we dig in further to understand what’s happening here?

**Comment by eagereyes** [comment]
You're right of course, I was misreading that closing curly brace and thought it would cause issues.

After some debugging and comparing to Plot docs today, I don't know what could be wrong. Both Plot and docs are successfully sending pings (they didn't when I looked into this last week, but that was some kind of GA issue). I'm seeing 204 return codes for both. And yet, we're getting traffic data for `/plot` now, but not for `/documentation`.

I will look into this again tomorrow, perhaps I can get another set of eyes to figure out what's wrong/different.

**Comment by eagereyes** [comment]
Looks like I was chasing a ghost, closing…

**Pull request closed without merging**
