### PR TITLE
added HTML cell and fixed a line in the SQL cell

### PR DESCRIPTION
**Pull request by pstuffa**
Adds a new HTML cell section.

### CODE REVIEW

**Comment by pstuffa** [comment]
@eagereyes do you mind taking a quick read through? I don't think there's much else to the HTML cell...

**Review by eagereyes — APPROVED** [review]
Short and sweet! :) Is it worth mentioning SVG here, as in being able to use (mostly) static SVG here too? I guess we can expand this later to cover more uses (also layout for old-school dashboards, etc.)

**Comment by pstuffa** [comment]
Not a bad idea! I'll mention that. One sec

**Comment by pstuffa** [comment]
@eagereyes added and I also did an example with HTL

**Comment by eagereyes** [comment]
Nice! This can be fleshed out further, but I think it's a nice start and looks better with a bit more content now

**Comment by pstuffa** [comment]
Great! Going to merge.

**Pull request merged**
