### PR TITLE
Collections page, links to quick guides and tutorials

### PR DESCRIPTION
**Pull request by eagereyes**
Migrates [the Collections page](https://observablehq.com/@observablehq/collections?collection=@observablehq/editing-publishing-collaborating#collectionOptions) and adds sidebar links to tutorials and quick guides.

I've used the .screenshot class here, but made an adjustment to 20px for the bottom margin, because 40px seems excessive

Also, I dropped that weird final section from the Collections page

### CODE REVIEW

**Review by jpe442 — CHANGES_REQUESTED** [review]
You have this in `docs/learn/collections`. Can you change to `docs/collections/collections.md`?

**Comment by eagereyes** [comment]
Okay, done!

**Review by jpe442 — APPROVED** [review]
LGTM!

**Review by jpe442 — APPROVED** [review]
LGTM

**Pull request merged**
