### PR TITLE
Add docs for schedules and notifications

### PR DESCRIPTION
**Pull request by tophtucker**
image

image

To-do:
- [x] Add screenshots for notification examples

### CODE REVIEW

**Comment by eagereyes** [comment]
I'm a bit unclear about the Timing table at the top. Does "Every 10 minutes around :x2" mean at 2, 12, 22 minutes past the hour? Do we want to spell this out?

Also, we don't adjust for daylight savings time I figure, so we should specify both xDT and xST

**Comment by eagereyes** [comment]
The notifications page talks about a Slack bot, do we have any docs on that we can link to?

**Comment by tophtucker** [comment]
>Does "Every 10 minutes around :x2" mean at 2, 12, 22 minutes past the hour? Do we want to spell this out?

Ah, yeah, it does. It’ll vary based on our queue’s backlog; maybe it would be better to just not get specific there.

**Review by eagereyes — APPROVED** [review]

**Comment by tophtucker** [comment]
Put up screenshots, read it all over again, will merge in the morning as soon as feature flag is removed (https://github.com/observablehq/observablehq/issues/14953).

**Pull request merged**
